### ISSUE TITLE
groupadd: GID '1000' already exists

### ISSUE THREAD

**Issue by Skylinar** [n4mlz/IcedTea-Docker#1]
Thanks for creating this.

I'm running into an issue when executing `docker compose up -d`

```
 => ERROR [main 3/9] RUN groupadd -g 1000 user &&     useradd -m -s /bin/bash -u 1000 -g 1000 -G sudo user &&     ec  0.1s 
------                                                                                                                     
 > [main 3/9] RUN groupadd -g 1000 user &&     useradd -m -s /bin/bash -u 1000 -g 1000 -G sudo user &&     echo user:user | chpasswd &&     echo "user   ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers:                                                     
0.075 groupadd: GID '1000' already exists
------
failed to solve: process "/bin/sh -c groupadd -g $GID $GROUPNAME &&     useradd -m -s /bin/bash -u $UID -g $GID -G sudo $USERNAME &&     echo $USERNAME:$PASSWORD | chpasswd &&     echo \"$USERNAME   ALL=(ALL) NOPASSWD:ALL\" >> /etc/sudoers" did not complete successfully: exit code: 4
```

**Comment by n4mlz** [comment]
Thank you for opening the issue!

This problem occurs because there is already a user with UID 1000 (ubuntu) and a group with GID 1000 in ubuntu:latest.

I have fixed this issue in the following commit, so please check it again:

https://github.com/n4mlz/IcedTea-Docker/commit/0884e7bd338eb031872447a4d7045bc36867bd25

(If you want to use the latest version of Ubuntu (24.04), try deleting the ubuntu user before creating a new one by adding `RUN id ubuntu && userdel ubuntu || true`.)

Thank you for your cooperation!

**Comment by Skylinar** [comment]
I should have mentioned that I am on Apple Silicon.

Issue is fixed on my side, thank you for your quick response!

**Comment by Skylinar** [comment]
fixed
